name: base-checks
on: [push]
permissions:
  contents: read
jobs:
  golangci:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]
    name: lint
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest
  testandbuild:
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    name: test-and-build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.18
      - uses: actions/checkout@v3
      - name: build
        run: go build ./...
      - name: test
        run: go test ./... -v
